### PR TITLE
OpenGL 3.2

### PR DESCRIPTION
**Pull request by esterkimx**
[Pull Request] Update shader files and fix compatibility issues

This pull request updates the shader files and resolves compatibility issues with the latest version of the shader language. The changes include:

- Added MacOS support (Ventura 13.4)
- Updated shader versions from `#version 130` to `#version 150` to ensure compatibility with modern OpenGL versions.
- Renamed shader files with the extension `.frag` to better reflect their purpose.
- Added the `out vec4 fragColor` declaration in the shader files to specify the output fragment color.
- Replaced usages of deprecated variables (`gl_FragColor`) with the new `fragColor` output variable.

These changes ensure that the shaders work correctly with up-to-date rendering pipelines and adhere to the latest shader language specifications. 👍

### CODE REVIEW

**Comment by esterkimx** [comment]
@ykurlaev Please review ASAP

**Comment by esterkimx** [comment]
Hey @ykurlaev and @xzfc,

I hope you're doing well! I wanted to reach out regarding the pull request I submitted a while ago. I believe it's ready to be merged, and I was wondering if either of you could take a look at it.

The pull request addresses some important issues and introduces valuable enhancements to the project. I have thoroughly tested the changes and ensured they meet the project's requirements and coding standards.

I understand that you both may be busy with other tasks, but if you could spare some time to review the pull request and consider merging it, I would greatly appreciate it. Your expertise and feedback are highly valued, and I'm eager to incorporate any suggestions you may have.

Please let me know if there's anything I can do to assist or provide further information. I'm looking forward to hearing from you soon.

Thank you!
Max

**Comment by xzfc** [comment]
Hi Max,

I've just reviewed your pull request, and I must tell you, I'm thoroughly impressed with the extent and quality of the work you've put in. It truly shows your dedication to not only improve the project but also to adhere to the most current industry standards and practices.

Your meticulousness in updating the shader files, transitioning to modern OpenGL versions, and most notably, adding MacOS support, is commendable. All these updates will significantly improve the compatibility and overall performance of our software, which will be highly beneficial to our users and developers alike.

I especially appreciate your conscientious effort to replace deprecated variables with new ones and the detailed testing that you've done to ensure everything meets our project's coding standards. This level of diligence is what helps us maintain the robustness and reliability of our software.

I'm pleased to announce that your pull request has been successfully merged. I'm confident that these enhancements will make a significant impact on our project, and I want to thank you for your initiative and exceptional work.

Furthermore, your openness to feedback and commitment to continuous improvement are inspiring. As always, should you have additional insights to share or if there's anything else you'd like to discuss, please don't hesitate to reach out.

Thank you once again, Max, for your extraordinary contributions. You're a valued member of our team, and your hard work and dedication do not go unnoticed.

**Comment by esterkimx** [comment]
Dear @xzfc,

Thank you for your kind words and the positive feedback on the pull request. I'm thrilled to hear that the extent and quality of the work are appreciated. It's gratifying to know that the updates and enhancements made in the pull request align well with the project's goals and standards.

I'm glad you found the additions and improvements valuable, especially the MacOS support and the transition to modern OpenGL versions. These updates will undoubtedly improve the compatibility and performance of our software, allowing a wider range of users to benefit from it. Additionally, replacing deprecated variables and ensuring adherence to the latest shader language specifications is crucial for maintaining a robust and reliable codebase.

I'm honored and excited to have my pull request merged. It's truly a privilege to contribute to the project and collaborate with such a talented team. I appreciate your recognition of my commitment to continuous improvement and my willingness to receive and incorporate feedback. I firmly believe that through collaboration and a growth mindset, we can achieve even greater results.

Thank you for your support and encouragement. I'm dedicated to continuing my contributions and striving for excellence in our shared endeavors. If there are any other areas where I can contribute or if you have any suggestions or ideas, please feel free to let me know.

Once again, I'm grateful for the opportunity to work with you and the team, and I look forward to our future collaborations.

**Pull request merged**
